version: "4" # Docker Compose 버전

services:
  database: # MariaDB 컨테이너 설정
    image: mariadb
    container_name: my-mariadb # MariaDB 컨테이너 이름
    ports:
      - "3307:3306" # 외부 포트 3307을 컨테이너 포트 3306에 연결
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: auth # 기본 생성할 데이터베이스 이름
    networks:
      - my-network # 사용자 정의 네트워크에 연결
    restart: always # MariaDB가 중단되면 자동으로 재시작
    volumes:
      - mariadb-data:/var/lib/mysql # 데이터를 컨테이너 외부에 유지
    env_file:
      - .env

  app: # Spring Boot 애플리케이션 컨테이너 설정
    build: # Dockerfile을 사용해 이미지 빌드
      context: . # 현재 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: Dockerfile # 사용할 Dockerfile
    container_name: my-app # Spring Boot 컨테이너 이름
    ports:
      - "8080:8080" # 외부 포트 8080을 컨테이너 포트 8080에 연결
    networks:
      - my-network # 사용자 정의 네트워크에 연결
    depends_on:
      - database
    restart: always # Spring Boot가 중단되면 자동으로 재시작
    env_file:
      - .env

networks:
  my-network: # 사용자 정의 네트워크 설정
    driver: bridge

volumes:
  mariadb-data: # 데이터 유지용 볼륨

