spring:
  application:
    name: SpringBootTemplate

  datasource:
    url: jdbc:mariadb://localhost:3306/auth
    username: root
    password: 비밀번호
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  accessTokenExpTime: 3600000  # 1?? (60 * 60 * 1000)
  refreshTokenExpTime: 604800000  # 7? (7 * 24 * 60 * 60 * 1000)
  secret: 598552aaff8e56c91489540619ab3cb62fa2ae044a1158b9562464a606f9e820